# Site settings
title: ""
description: ""
url: "https://wtsdu.com" # Your GitHub Pages URL

# Build settings
markdown: kramdown
theme: minima

# Collections (for blog posts)
collections:
  posts:
    output: true

# Exclude files and folders from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults for collections
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true

# Permalinks
permalink: pretty

# Pagination settings (optional)
paginate: 5
paginate_path: "/blog/page:num/"

# Theme customization
minima:
  include_navbar_in_header: false
  include_footer_in_header: false

imagesurl: "/_gallery/photos/"
thumbsurl: "/_gallery/thumbs/"
