name: Update Blog
on:
  push:
    branches:
      - main
    paths:
      - public/_posts/**
  pull_request:
    branches:
      - main
    paths:
      - public/_posts/**
permissions:
  id-token: write
  actions: write
  pages: write
  contents: write
jobs:
  deploy:
    name: Update Blog Posts on Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses:  actions/checkout@v4
        with:
          persist-credentials: false
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
            REPO: self
            BRANCH: gh-pages
            FOLDER: public/_posts
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TARGET_DIR: _posts